# HCP Young Adult Data

---

### package imports and basic functions

---

In [1]:
import os
import gc
import sys
import glob
import json
import random
import datetime
import importlib
import itertools
import numpy as np
from scipy import spatial
import scipy.sparse as sparse
import scipy.stats as stats
import pandas as pd
import nibabel as nib
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import boto3
from tqdm.auto import tqdm


In [2]:
%load_ext autoreload
%autoreload 2

# Path to add to src folder (to use local version of spectranorm)
sys.path.append(os.path.abspath("/mountpoint/code/projects/spectranorm/package/spectranorm/src/"))

from spectranorm import snm


In [3]:
class MyNumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)


def ensure_dir(file_name):
    os.makedirs(os.path.dirname(file_name), exist_ok=True)
    return file_name


def list_dirs(path=os.getcwd()):
    files = glob.glob(os.path.join(path, '*'))
    files = [x for x in files if os.path.isdir(x)]
    return files


def file_exists(file_name, path_name=os.getcwd()):
    return os.path.isfile(os.path.join(path_name, file_name))


def write_json(json_obj, file_path):
    with open(file_path, 'w') as outfile:
        json.dump(json_obj, outfile, sort_keys=True, indent=4,
                  cls=MyNumpyEncoder)
    return json_obj


def write_np(np_obj, file_path):
    with open(file_path, 'wb') as outfile:
        np.save(outfile, np_obj)


In [4]:
# path setting
main_dir = os.path.abspath('../../..')


## Downloading data from HCP bucket storage

---

In [5]:
session = boto3.session.Session(profile_name='hcp')
s3 = session.client('s3')


In [6]:
paginator = s3.get_paginator('list_objects_v2')

subjects = [cur["Prefix"].split('/')[1] for page in paginator.paginate(Bucket='hcp-openaccess', Prefix="HCP_1200/", Delimiter="/") for cur in page.get("CommonPrefixes", [])]


In [8]:
len(subjects)


1113

In [ ]:
def get_list_of_items(directory):
    for page in paginator.paginate(Bucket='hcp-openaccess', Prefix=directory, Delimiter='/'):
        # Files directly under directory
        for obj in page.get('Contents', []):
            print("File:", obj['Key'])

        # Subfolders directly under directory
        for cp in page.get('CommonPrefixes', []):
            print("Subfolder:", cp['Prefix'])
    
get_list_of_items("HCP_1200/100206/T1w/100206/stats/")


In [ ]:
# # download all MSMAll thickness values
# for subject in subjects:
#     try:
#         s3.download_file(
#             'hcp-openaccess',
#             f'HCP_1200/{subject}/MNINonLinear/fsaverage_LR32k/{subject}.thickness_MSMAll.32k_fs_LR.dscalar.nii',
#             ensure_dir(f'/mountpoint/data/HCP_1200/{subject}/MNINonLinear/fsaverage_LR32k/{subject}.thickness_MSMAll.32k_fs_LR.dscalar.nii'),
#         )
#     except:
#         print(f'NOTE: {subject} download failed')


In [21]:
# download all freesurfer thickness values
items = [
    "lh.white", "rh.white",
    "lh.pial", "rh.pial",
    "lh.thickness", "rh.thickness",
    "lh.orig.nofix", "rh.orig.nofix",
    "lh.sphere.reg", "rh.sphere.reg",
]
for subject in tqdm(subjects):
    for item in items:
        try:
            s3.download_file(
                'hcp-openaccess',
                f'HCP_1200/{subject}/T1w/{subject}/surf/{item}',
                ensure_dir(f'/mountpoint/data/HCP_1200/{subject}/T1w/{subject}/surf/{item}'),
            )
        except:
            print(f'NOTE: {subject}: {item} download failed')


  0%|          | 0/1113 [00:00<?, ?it/s]

## Extracting data

---

In [9]:
hcpya_dir = '/mountpoint/data/HCP_1200/'
hcpya_subjects = [x.split('/')[-1] for x in list_dirs(hcpya_dir)]
len(hcpya_subjects)


1113

In [10]:
items = [
    "lh.white", "rh.white",
    "lh.pial", "rh.pial",
    "lh.thickness", "rh.thickness",
    "lh.orig.nofix", "rh.orig.nofix",
    "lh.sphere.reg", "rh.sphere.reg",
]
hcpya_valid_subjects = [
    subject for subject in hcpya_subjects
    if all([
        file_exists(f'/mountpoint/data/HCP_1200/{subject}/T1w/{subject}/surf/{item}','')
        for item in items
    ])
]
len(hcpya_valid_subjects)


1113

In [123]:
# ignore warning
nib.imageglobals.logger.setLevel(40)


In [140]:
# Store high-resolution thickness for each individual in a separate file
for idx, subject in enumerate(tqdm(hcpya_valid_subjects)):
    sub_dir = f"{idx:02d}"[-2:]
    freesurfer_directory = f"/mountpoint/data/HCP_1200/{subject}/T1w/{subject}/"
    transformed_fslr_thickness = snm.utils.nitools.compute_fslr_thickness(freesurfer_directory)
    np.save(
        ensure_dir(f"/mountpoint/data/normative/fs_LR_32k/HCP-YA/{sub_dir}/{subject}.thickness.fslr.npy"),
        transformed_fslr_thickness.astype(np.float32)
    )


  0%|          | 0/1113 [00:00<?, ?it/s]

In [6]:
# Old code, not used now
# %%time
# # create a numpy array to populate
# hcpya_data = np.zeros((len(hcpya_valid_subjects), 59412))

# for idx, subject in enumerate(hcpya_valid_subjects):
#     hcpya_data[idx] = nib.load(f'{hcpya_dir}/{subject}/MNINonLinear/fsaverage_LR32k/{subject}.thickness_MSMAll.32k_fs_LR.dscalar.nii').get_fdata().reshape(-1)


pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
pixdim[1,2,3] should be non-

CPU times: user 2min 53s, sys: 5.48 s, total: 2min 59s
Wall time: 3min 44s


In [11]:
unrestricted = pd.read_csv(f'{hcpya_dir}/unrestricted_sination_5_23_2019_21_35_35.csv')
restricted = pd.read_csv(f'{hcpya_dir}/0.RESTRICTED_sination_5_23_2019_21_32_45.csv')


In [38]:
# unrestricted[["MRsession_Scanner_3T", 'MRsession_Scans_3T', 'MRsession_Label_3T',]]
unrestricted["MRsession_Scanner_3T"].unique()


array([nan, 'HCP3T'], dtype=object)

In [12]:
hcpya_ages = np.array(
    [
        float(restricted[restricted['Subject'] == int(subject)]['Age_in_Yrs'])
        for subject in hcpya_valid_subjects
    ]
)


/tmp/ipykernel_1996334/3706383679.py:3: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  float(restricted[restricted['Subject'] == int(subject)]['Age_in_Yrs'])


In [14]:
hcpya_genders = np.array(
    [
        unrestricted[unrestricted['Subject'] == int(subject)]['Gender'].copy()
        for subject in hcpya_valid_subjects
    ]
)[:, 0]
hcpya_genders


array(['F', 'F', 'F', ..., 'F', 'F', 'F'], dtype=object)

In [ ]:
hcpya_ids = np.array(
    [
        str(unrestricted[unrestricted['Subject'] == int(subject)]['Subject'].values[0])
        for subject in hcpya_valid_subjects
    ]
)
hcpya_ids

In [16]:
hcpya_enos = np.array(
    [
        float(snm.utils.nitools.compute_total_euler_number(
            f"/mountpoint/data/HCP_1200/{subject}/T1w/{subject}/"
        )) for subject in tqdm(hcpya_valid_subjects)
    ]
)
hcpya_enos

  0%|          | 0/1113 [00:00<?, ?it/s]

array([ -92.,  -82.,  -88., ..., -118.,  -62.,  -78.])

In [17]:
hcpya_mean_thickness = np.array(
    [
        np.load(f"/mountpoint/data/normative/fs_LR_32k/HCP-YA/{(idx%100):02d}/{subject}.thickness.fslr.npy").mean()
        for idx, subject in enumerate(tqdm(hcpya_valid_subjects))
    ]
)
hcpya_mean_thickness

  0%|          | 0/1113 [00:00<?, ?it/s]

array([2.6621008, 2.6617508, 2.732261 , ..., 2.5383532, 2.7164469,
       2.5542564], dtype=float32)

## Storing cleaned data

---

In [23]:
# mean thickness stored as csv
# hcpya_mean_thickness = np.mean(hcpya_data, axis=1)
hcpya_df = pd.DataFrame({'age': hcpya_ages, 'thickness': hcpya_mean_thickness, 'sex': hcpya_genders, 'subject_ID': hcpya_ids, 'euler_no': hcpya_enos, 'subject_folder': hcpya_valid_subjects, 'subject_index':np.arange(len(hcpya_valid_subjects))})
dataset_name = 'HCP-YA'
hcpya_df['dataset'] = dataset_name
hcpya_df.to_parquet(ensure_dir(f'/mountpoint/data/normative/datasets/{dataset_name}/demography.parquet'))


In [133]:
np.save(
    ensure_dir("/mountpoint/data/normative/datasets/HCP-YA/subjects.npy"),
    np.array(hcpya_valid_subjects)
)

In [13]:
# # valid subject names as json
# write_json(hcpya_valid_subjects, ensure_dir(f'{main_dir}/data/json/valid_subjects_{dataset_name}.json'));


In [14]:
# # high-resolution thickness as npy
# write_np(hcpya_data, ensure_dir(f'{main_dir}/data/npy/thickness_{dataset_name}.npy'));


In [ ]:
hcpya_df.head()
