# HCP Development Data

---

### package imports and basic functions

---

In [17]:
import os
import gc
import sys
import glob
import json
import random
import datetime
import importlib
import itertools
import numpy as np
from scipy import spatial
import scipy.sparse as sparse
import scipy.stats as stats
import pandas as pd
import nibabel as nib
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import boto3
from tqdm.auto import tqdm


In [18]:
%load_ext autoreload
%autoreload 2

# Path to add to src folder (to use local version of spectranorm)
sys.path.append(os.path.abspath("/mountpoint/code/projects/spectranorm/package/spectranorm/src/"))

from spectranorm import snm


In [19]:
class MyNumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)


def ensure_dir(file_name):
    os.makedirs(os.path.dirname(file_name), exist_ok=True)
    return file_name


def list_dirs(path=os.getcwd()):
    files = glob.glob(os.path.join(path, '*'))
    files = [x for x in files if os.path.isdir(x)]
    return files


def file_exists(file_name, path_name=os.getcwd()):
    return os.path.isfile(os.path.join(path_name, file_name))


def write_json(json_obj, file_path):
    with open(file_path, 'w') as outfile:
        json.dump(json_obj, outfile, sort_keys=True, indent=4,
                  cls=MyNumpyEncoder)
    return json_obj


def write_np(np_obj, file_path):
    with open(file_path, 'wb') as outfile:
        np.save(outfile, np_obj)


In [20]:
# path setting
main_dir = os.path.abspath('../../..')


## Downloading data from NDA s3 bucket storage

---

In [ ]:
# downloaded by:
# downloadcmd -dp 1185256 -u 'sinamansourlakouraj' -d HCPDevImgManifestBeh


In [ ]:
# %%bash

# # get list of s3 links to be downloaded
# cat /mountpoint/data/HCP_Development/HCPDevImgManifestBeh/datastructure_manifest.txt \
# | grep PreprocStrucRecommended \
# | cut -f6 \
# | sed 's/"//g' \
# | grep MNINonLinear/fsaverage_LR32k \
# | grep thickness_MSMAll.32k_fs_LR.dscalar.nii \
# | grep HCD \
# > /mountpoint/data/NDA/HCPD_thickness_s3links.txt
# # | head


In [ ]:
# %%bash

# # make folder to store data in
# mkdir /mountpoint/data/HCP_Development


In [ ]:
# %%bash

# # Download the related files:
# # cd /mountpoint/data/
# # downloadcmd -dp 1205202 -t /home/sina/Documents/Research/Codes/NDA/HCPD_thickness_s3links.txt -u 'sinamansourlakouraj' -d HCP_Development -wt 8

# # other detail in: /mountpoint/code/environments/venv_3.8.10/lib/python3.8/site-packages/NDATools/clientscripts/config/settings.cfg


In [14]:
%%bash

# get list of s3 links to be downloaded
# using freesurfer processed files instead

cat /mountpoint/data/HCP_Development/HCPDevImgManifestBeh/datastructure_manifest.txt \
| grep PreprocStrucFreesurfer \
| grep \
-e 'lh.white"' -e 'lh.pial"' -e 'lh.thickness"' -e 'lh.orig.nofix"' -e 'lh.sphere.reg"' \
-e 'rh.white"' -e 'rh.pial"' -e 'rh.thickness"' -e 'rh.orig.nofix"' -e 'rh.sphere.reg"' \
| cut -f6 \
| sed 's/"//g' \
> /mountpoint/data/NDA/HCPD_freesurfer_thickness_s3links.txt
# | head -n 12


In [ ]:
# %%bash

# # Download the related files:
# cd /mountpoint/data/
# downloadcmd -dp 1205202 -t /home/sina/Documents/Research/Codes/NDA/HCPD_freesurfer_thickness_s3links.txt -u 'sinamansourlakouraj' -d HCP_Development -wt 8

# # other detail in: /mountpoint/code/environments/venv_3.8.10/lib/python3.8/site-packages/NDATools/clientscripts/config/settings.cfg


## Extracting data

---

In [21]:
hcpd_dir = '/home/ubuntu/mediafluxmount/Datasets/HCPDevelopment/Subjects/'
hcpd_subjects = [x.split('/')[-1] for x in list_dirs(hcpd_dir)]
len(hcpd_subjects)


652

In [22]:
items = [
    "lh.white", "rh.white",
    "lh.pial", "rh.pial",
    "lh.thickness", "rh.thickness",
    "lh.orig.nofix", "rh.orig.nofix",
    "lh.sphere.reg", "rh.sphere.reg",
]
hcpd_valid_subjects = [
    subject for subject in hcpd_subjects
    if all([
        file_exists(f'/mountpoint/data/HCP_Development/fmriresults01/{subject}/T1w/{subject}/surf/{item}','')
        for item in items
    ])
]
len(hcpd_valid_subjects)


652

In [23]:
# ignore warning
nib.imageglobals.logger.setLevel(40)


In [24]:
# Store high-resolution thickness for each individual in a separate file
for idx, subject in enumerate(tqdm(hcpd_valid_subjects)):
    sub_dir = f"{idx:02d}"[-2:]
    freesurfer_directory = f"/mountpoint/data/HCP_Development/fmriresults01/{subject}/T1w/{subject}/"
    transformed_fslr_thickness = snm.utils.nitools.compute_fslr_thickness(freesurfer_directory)
    np.save(
        ensure_dir(f"/mountpoint/data/normative/fs_LR_32k/HCP-D/{sub_dir}/{subject}.thickness.fslr.npy"),
        transformed_fslr_thickness.astype(np.float32)
    )


  0%|          | 0/652 [00:00<?, ?it/s]

In [25]:
hcpd_demography = pd.read_csv(
    f'/mountpoint/data/NDA/AllHCPdataAgingDevelop/fmriresults01.txt',
    delimiter='\t',
    skiprows=[1],
    header=0
)


In [65]:
hcpd_info = pd.read_csv(
    f'/mountpoint/data/NDA/AllHCPdataAgingDevelop/ndar_subject01.txt',
    delimiter='\t',
    skiprows=[1],
    header=0
)


In [28]:
hcpd_ages = np.array(
    [
        float(hcpd_demography[hcpd_demography['src_subject_id'] == (subject[:-6])]['interview_age'].values[0])/12
        for subject in hcpd_valid_subjects
    ]
)
hcpd_ages[:3]

array([11.91666667, 16.        ,  9.16666667])

In [67]:
hcpd_sites = np.array(
    [
        f"site:{hcpd_info.loc[hcpd_info['src_subject_id'] == subject[:-6], 'site'].iloc[0]}"
        for subject in hcpd_valid_subjects
    ]
)
hcpd_sites[:3]

array(['site:WashU', 'site:Harvard', 'site:Harvard'], dtype='<U12')

In [29]:
gender_dict = {'M': 0, 'F': 1}
hcpd_genders = np.array(
    [
        hcpd_demography[hcpd_demography['src_subject_id'] == (subject[:-6])]['sex'].values[0]
        for subject in hcpd_valid_subjects
    ]
)
hcpd_genders[:3]

array(['M', 'F', 'F'], dtype='<U1')

In [ ]:
hcpd_ids = np.array(
    [
        str(hcpd_demography[hcpd_demography['src_subject_id'] == (subject[:-6])]['src_subject_id'].values[0])
        for subject in hcpd_valid_subjects
    ]
)
hcpd_ids[:3]

In [31]:
hcpd_enos = np.array(
    [
        float(snm.utils.nitools.compute_total_euler_number(
            f"/mountpoint/data/HCP_Development/fmriresults01/{subject}/T1w/{subject}/"
        )) for subject in tqdm(hcpd_valid_subjects)
    ]
)
hcpd_enos[:3]

  0%|          | 0/652 [00:00<?, ?it/s]

array([-102.,  -44.,  -96.])

In [32]:
hcpd_mean_thickness = np.array(
    [
        np.load(f"/mountpoint/data/normative/fs_LR_32k/HCP-D/{(idx%100):02d}/{subject}.thickness.fslr.npy").mean()
        for idx, subject in enumerate(tqdm(hcpd_valid_subjects))
    ]
)
hcpd_mean_thickness[:3]

  0%|          | 0/652 [00:00<?, ?it/s]

array([3.087997 , 2.9953651, 3.0241418], dtype=float32)

## Storing cleaned data

---

In [68]:
# mean thickness stored as csv
# hcpd_mean_thickness = np.mean(hcpd_data, axis=1)
hcpd_df = pd.DataFrame({'age': hcpd_ages, 'thickness': hcpd_mean_thickness, 'site': hcpd_sites, 'sex': hcpd_genders, 'subject_ID': hcpd_ids, 'euler_no': hcpd_enos, 'subject_folder': hcpd_valid_subjects, 'subject_index':np.arange(len(hcpd_valid_subjects))})
dataset_name = 'HCP-D'
hcpd_df['dataset'] = dataset_name
hcpd_df.to_parquet(ensure_dir(f'/mountpoint/data/normative/datasets/{dataset_name}/demography.parquet'))


In [34]:
np.save(
    ensure_dir("/mountpoint/data/normative/datasets/HCP-D/subjects.npy"),
    np.array(hcpd_valid_subjects)
)

In [ ]:
hcpd_df.head()
